name: Automation Build Image 
run-name: ${{github.event.head_commit.message}}
# 
on: 
  push: 
     tags: 
        - 'v*'

permissions: 
  contents: write
  packages: write

jobs: 
  build-docker-image:
      name: "Build Docker Image"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Login ghcr.io
          run: echo -n ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Build Docker image
          run: docker build . -t ghcr.io/${{github.repository}}:latest
  
        - name: Push to ghcr.io
          run: docker push ghcr.io/${{github.repository}}:latest
          
  release-linux-amd64:
      name: release linux/amd64
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: linux
          EXTRA_FILES: "LICENSE"